### ISSUE TITLE
Backend simplification & factorization

### ISSUE THREAD

**Issue by W95Psp** [cryspen/hax#154]
@cmester0 and I were discussing how we could simplify & factorize backends, let's summarize things here.

 There's a lot of boilerplate for implementing a backend currently:
 - tuples are `Construct` nodes with a particular name
 - field projections (ie `x.field`) are applications of one arg to a particularly named function
 - operators are function applications we need to re-structure in the backend
 - need to prefix/rename global names according to their kind (eg type, constructors, function names...)
 - other things, TODO

# Status / Roadmap
We are experimenting with a generic printer, that is now in `main`.

 - [ ] Drop the ["Rustish" printer](https://github.com/hacspec/hax/blob/eebfe9b38a621d924794379553a9b263ba7d32bd/engine/lib/print_rust.ml), replace it with the generic printer
 - [x] Add ProVerif backend: it is in `main`, and @jschneider-bensch is actively working on it!
 - [ ] Write a F\* backend based on the generic printer
 - [ ] Drop the existing F\* backend and the `[fstar-surface-ast](https://github.com/hacspec/hax/tree/main/engine/backends/fstar/fstar-surface-ast)` folder (that contains a part of F\*'s OCaml sources)

**Comment by W95Psp** [comment]
Related: #252, #355

**Comment by W95Psp** [comment]
Related:  
 - #533
 - #942

**Comment by maximebuyse** [comment]
This is obsolete with the new Rust infrastructure
